# Generated by Django 3.0.4 on 2020-03-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbum_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='likes_counter',
            field=models.IntegerField(default=0),
        ),
    ]
